### ISSUE TITLE
Can´t access AclManager

### ISSUE THREAD

**Issue by thiagojeffery** [ivanamat/cakephp3-app#1]
In this step I can´t access /AclManager
"Log in on /Users/login as the user created, go to /AclManager and click on Restore to default to create ACOs and AROs automatically."
(Error: Call to a member function alias() on boolean 
File C:\xampp\htdocs\my_app\vendor\ivanamat\cakephp3-aclmanager\src\Controller\AclController.php 
Line: 90)
Line 90 : $this->paginate[$this->{$aro}->alias()] = array(
                'recursive' => -1,
                'limit' => $limit
            );

I think this can fix: Configure::write('AclManager.models', array('Groups', 'Roles', 'Users'));

**Comment by vibrationpixel** [comment]
that's right, you need to **uncomment** in cakephp3-aclmanager > config > bootstrap.php line 30
 
> Configure::write('AclManager.aros', array('Groups', 'Roles', 'Users'));

**Comment by ivanamat** [comment]
Hi @thiagojeffery,

First of all, I apologize for taking so long to respond, I have changed my address, my internet service provider has left me without services for almost three months and then the laptop has touched me to take it to repair.

In the section Getting Started, I explain, although perhaps not very well, that in your bootstrap file you must include the following configuration, depending on the AROS that you are going to use (Attachment configuration according to the example).

Configure::write('AclManager.aros', array('Groups', 'Roles', 'Users'));

https://github.com/ivanamat/cakephp3-aclmanager#getting-started

Try adding the configuration to your bootstrap file and tell me if it works correctly.

Regards!

**Comment by mss-mohdali** [comment]
I am getting the same error " Fatal error: Call to a member function alias() on boolean in /var/www/html/cakeapp/vendor/ivanamat/cakephp3-aclmanager/src/Controller/AclController.php on line 90"

I have used Configure::write('AclManager.aros', array('Groups', 'Roles', 'Users')); in bootstrap.pphp but getting the same error.

**Comment by ivanamat** [comment]
Hi @mss-mohdali ,

Put this line "Configure::write('AclManager.aros', array('Groups', 'Roles', 'Users'));" before load the plugin:

```
Configure::write('AclManager.aros',` array('Groups', 'Roles', 'Users'));

Plugin::load('Acl', ['bootstrap' => true]);
Plugin::load('AclManager', ['bootstrap' => true, 'routes' => true]);
```

Tell me if this solves the problem please.

Regards!

**Comment by ivanamat** [comment]
I will try to update this repository as soon as possible, since there have been updates of the AclManager plugin.

**Comment by mss-mohdali** [comment]
Thanks for update.it solves the issue and i am able to see the AclManager view . But when i click on Manage Groups then it says me to login "Please login" . 

When i logged in then i am getting the below error :-1: 
`Error: A route matching "array ( 'controller' => 'Pages', 'action' => 'display', 'prefix' => false, 'plugin' => 'AclManager', '_ext' => NULL, )" could not be found.

None of the currently connected routes match the provided parameters. Add a matching route to config/routes.php

The passed context was:

[
	'_base' => '/cakeapp',
	'_port' => null,
	'_scheme' => 'http',
	'_host' => 'localhost',
	'params' => [
		'plugin' => 'AclManager',
		'controller' => 'Acl',
		'action' => 'index',
		'_ext' => null,
		'pass' => [],
		'_matchedRoute' => '/AclManager',
		'isAjax' => false
	]
]`

**Comment by ivanamat** [comment]
Please, read this https://github.com/ivanamat/cakephp3-aclmanager or this piece https://github.com/ivanamat/cakephp3-aclmanager#create-a-group-role-and-user for create groups, roles or users.

Regards!

**Comment by mss-mohdali** [comment]
I have created the groups , roles and users as per above links and updated the Aco and Aro tables from ACL manager .But when i remove "$this->Auth->allow()" then i am getting the same error.

**Comment by ivanamat** [comment]
Please, read this part of the documentation https://github.com/ivanamat/cakephp3-aclmanager#access-the-plugin (or read the full documentation)

Regards!

**Comment by mss-mohdali** [comment]
I have read the full documentation and working the same but same error is coming . It is not working for me.

**Comment by ivanamat** [comment]
Have you tried to access http://www.yourdomain.com/AclManager and run "Update ACOs and AROs and set default values" before remove "$this->Auth->allow()"?

**Comment by ivanamat** [comment]
@mss-mohdali 

Has your issue been solved?

**Comment by mss-mohdali** [comment]
I am able to access http://www.yourdomain.com/AclManager and  "Update ACOs and AROs both tables updated successfully as default values after that i removed  "$this->Auth->allow()" then it redirect me on login user . When i logged-in then same error is coming .

If i logged-in and add "$this->Auth->allow()" then error is removed and able to access the permission views for groups, roles and users . But notthing is displaying in group listing . Check the below url:-
[https://s.nimbus.everhelper.me/share/1143223/t6ighwv8heo2t2rxzh53](url)

**Comment by ivanamat** [comment]
¿Have you wrote any route?

"`Error: A route matching "array ( 'controller' => 'Pages', 'action' => 'display', 'prefix' => false, 'plugin' => 'AclManager', '_ext' => NULL, )" could not be found."

**Comment by mss-mohdali** [comment]
No , i have not wrote any route . I just install using composer as per instruction in documentation:-
"A skeleton for creating applications with CakePHP 3.x. The skeleton has been preloaded with the Acl and AclManager plugins. Manages groups, roles, users and ACL. "

**Comment by ivanamat** [comment]
Ok @mss-mohdali , this afternoon I check, I update cakephp-app with the latest version of the plugin, I test it and I'll let you know when I have it updated.

Regards!

**Comment by mss-mohdali** [comment]
Thank you for your support . I will wait for your next update.

**Comment by ivanamat** [comment]
Hi @mss-mohdali 

Try the latest version creating new project, please.
https://github.com/ivanamat/cakephp3-app/releases/tag/1.2

I have tried to create a project from the beginning and no problem, I was able to configure it correctly and make it work.
 
Tell me if you can configure it and make it work please.

Regards!

**Comment by PrajapatiAakash** [comment]
@mss-mohdali

Has your issue been solved?

**Comment by ivanamat** [comment]
Hi @mss-mohdali 

Yes, the issue has been resolved and the version has been updated.

Regards!

**Comment by nikhildalal** [comment]
When I try to use AclManager with only groups i.e. with the setting in bootstrap as 
Configure::write('AclManager.aros', array('Groups'));
then the AclManager fails and the error log says 
Error: [Cake\Core\Exception\Exception] AclNode::node() - Couldn't find Aros node identified by "Array
(
    [Aros0.model] => Users
    [Aros0.foreign_key] => 1
)
"
Request URL: /admin/AclManager/

Any idea whats wrong ?
